### ISSUE TITLE
3c.exchange ignoring paper orders

### ISSUE THREAD

**Issue by riodda** [bogdanteodoru/py3cw#5] opened 2020-07-15 07:34 UTC
Hi, from the last 10 days 3c.exchange is ignoring totally all the paper orders, anybody else is having this issue ? Thanks.

**Comment by bogdanteodoru** [comment] 2020-07-15 11:17
@riodda what do you mean "ignoring" ? Do you get an OK response from 3commas or any error whatsoever?

**Comment by riodda** [comment] 2020-07-16 12:17
No errors, it simply ignores the orders while i get corretly all the prices.

**Comment by bogdanteodoru** [comment] 2020-07-16 14:14
@riodda I'll link this up to the official GitHub because it seems to be a problem from their side.

**Comment by riodda** [comment] 2020-07-17 07:08
No I actually receive and error:

Order Result {'error': 'signature_invalid', 'error_description': 'Provided signature is invalid'}

But my api hasn't changed and my code hasn't changed.
i'm using 3c.exchange i read somewhare that the endpoint url has changed for 3c.exchange.
The strange thing is that the market data is downloaded correctly.

**Comment by bogdanteodoru** [comment] 2020-07-17 10:39
Hmm... seems that the signature is invalid. Can you re-generate the API keys and try to see if it works with the new ones?

**Comment by riodda** [comment] 2020-07-17 15:43
I have re generated api but i still have the same error.
my order function is 

`def close_all_deals(_bot_id):
    _error,_data = p3cw.request(
    entity='bots', 
    action='panic_sell_all_deals', 
    action_id=_bot_id,
    payload={ 'bot_id': _bot_id})    
    if _error == None:
        return True
    else:
        return False

def start_deal(_bot_id):
    _error,_data = p3cw.request(
    entity='bots', 
    action='start_new_deal', 
    action_id=_bot_id,
    payload={ 'bot_id': _bot_id})
    if _error == None:
        return _data
    else:
        return _error`

**Comment by riodda** [comment] 2020-07-18 08:15
What about the end url ? Should be different now between 3c.exchange and 3commas.io ?

**Comment by bogdanteodoru** [comment] 2020-07-18 14:51
@riodda, the base endpoint is: https://api.3commas.io/public/api

**Comment by riodda** [comment] 2020-07-19 07:17
> @riodda, the base endpoint is: https://api.3commas.io/public/api

Wasn't replaced for 3c.exchange ?

**Comment by bogdanteodoru** [comment] 2020-07-19 16:59
This what I found on their Github so not sure.

**Comment by MoroZvlg** [comment] 2020-07-20 06:20
https://github.com/bogdanteodoru/py3cw/pull/4

**Comment by bogdanteodoru** [comment] 2020-07-20 07:16
@riodda, @MoroZvlg confirmed that in fact, 3c.exchange endpoint ignores paper trades.

**Comment by MoroZvlg** [comment] 2020-07-20 08:02
What?
you have an "invalid_signature" error. How it's related to "ignores paper trades". 
As I understand from current issue "ivalid_signature" was a real problem

**Comment by riodda** [comment] 2020-07-20 08:52
Signature error is only for trades, with the same api you can use all the rest of the api.

**Comment by bogdanteodoru** [comment] 2020-07-21 06:43
@riodda I have deployed a new version (0.0.15). Please update to that and see if you encounter any other issues. The "invalid signature" problem should be fixed. Thanks.

**Closed by bogdanteodoru** 2020-07-21 06:43 UTC
